### ISSUE TITLE
DHCP offer does not get delivered to docker container

### ISSUE THREAD

**Issue by alolage-nx** [zauberhaus/rest2dhcp#2]
I have below configuration. 

VM1 : Rest2DHCP API server with 2 interfaces, eth0 (10.0.126.132) and eth1 (10.0.11.102)
VM2 : Running ubuntu DHCP Server

I am running  rest2dhcp server as, "docker run  -e SERVER="10.0.126.249" -e RELAY="10.0.11.102" -e MODE=udp -p 8080:8080 -p 67:67/udp  zauberhaus/rest2dhcp". 

I see the DHCP offer coming to eth1 but it does not get delivered to docker0 interface.

Am I missing some configuration to get this working?

**Comment by zauberhaus** [comment]
This sounds like a problem with the docker configuration.
Is docker really listening on the eth1 interface?

Which DHCP server are you using on the Ubuntu server? Some DHCP servers have special implementations of the relay mode. This varies from incorrect ports for the response (not UDP port 67) or missing response to DHCP request.

For example, dnsmasq only works if the flag dhcp-authoritative is set.
